In [3]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [4]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  Redirection  \
0           mylust.com        0        0           1          3            0   
1          plarium.com        0        0           1          5            0   
2  c1511482.ferozo.com        0        0           0          4            0   
3      momoshop.com.tw        0        0           1          2            0   
4       binance10x.com        0        0           0          0            0   

   https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  \
0             0        1              0           0            1           1   
1             0        0              0           0            1           0   
2             0        0              0           0            1           0   
3             0        0              0           0            1           0   
4             0        1              0           0            1           0   

   Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  Label  
0           1       0           0            1             0      0  
1           1       0           0            1             0      0  
2           1       1           1            1             1      1  
3           1       1           1            1             1      0  
4           0       0           0            1             0      1

In [5]:
X = data.drop(['Domain', 'Label'], axis=1)

In [6]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          3            0             0   
1        0        0           1          5            0             0   
2        0        0           0          4            0             0   
3        0        0           1          2            0             0   
4        0        0           0          0            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        1              0           0            1           1           1   
1        0              0           0            1           0           1   
2        0              0           0            1           0           1   
3        0              0           0            1           0           1   
4        1              0           0            1           0           0   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             0  
2       1           1            1             1  
3       1           1            1             1  
4       0           0            1             0

In [11]:


#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])


X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)


# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]


# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)




LogisticRegression Metrics:
Accuracy: 0.8066666666666666
Precision: 0.8286695601851852
Recall: 0.8066666666666666
F1 Score: 0.8028065391338914
Confusion Matrix:
[[1433   93]
 [ 487  987]]

SVC Metrics:
Accuracy: 0.8366666666666667
Precision: 0.8697422660353252
Recall: 0.8366666666666667
F1 Score: 0.8324122980330173
Confusion Matrix:
[[1507   19]
 [ 471 1003]]

RandomForestClassifier Metrics:
Accuracy: 0.8633333333333333
Precision: 0.8681446885352558
Recall: 0.8633333333333333
F1 Score: 0.8627204421628212
Confusion Matrix:
[[1409  117]
 [ 293 1181]]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(



MLPClassifier Metrics:
Accuracy: 0.8473333333333334
Precision: 0.8506788669122584
Recall: 0.8473333333333334
F1 Score: 0.8468049023127385
Confusion Matrix:
[[1373  153]
 [ 305 1169]]

KNeighborsClassifier Metrics:
Accuracy: 0.8433333333333334
Precision: 0.8448678477238849
Recall: 0.8433333333333334
F1 Score: 0.8430409831596589
Confusion Matrix:
[[1344  182]
 [ 288 1186]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8633333333333333
Precision: 0.8686133550931594
Recall: 0.8633333333333333
F1 Score: 0.8626698257721712
Confusion Matrix:
[[1413  113]
 [ 297 1177]]
